#!/bin/bash
cc  push_swap.c libft.c libft_second.c min_sort.c operation_function.c push_swap_utils.c -g
rm push_swap
mv a.out push_swap
# cc  -g -fsanitize=address push_swap.c libft.c libft_second.c min_sort.c operation_function.c push_swap_uti0ls.c
